GET https://localhost:8080/dev/hallo
Authorization: Bearer {{accessTokenEndless}}

###
POST https://localhost:8080/token/
Content-Type: application/json

{
  "username": "user",
  "password": "password"
}

###
POST https://localhost:8080/dev/password
Content-Type: application/json

{
  "password": "password"
}

###

GET https://localhost:8080/dev/dgraph/v
Authorization: Bearer {{accessTokenEndless}}


###
GET https://localhost:8080/yearscheme/generator/2021/
Authorization: Bearer {{accessTokenEndless}}


###

POST https://localhost:8080/yearscheme/generator/2021/save/
Authorization: Bearer {{accessTokenEndless}}

###
GET https://localhost:8080/yearscheme/y2021/
Authorization: Bearer {{accessTokenEndless}}

###
GET https://localhost:8080/yearscheme/0x116d5/
Authorization: Bearer {{accessTokenEndless}}

###
DELETE https://localhost:8080/yearscheme/0x116d5/
Authorization: Bearer {{accessTokenEndless}}

###
POST https://localhost:8080/dayprofilecondition/create/DayOfMonthDayProfileCondition?saveToDB=true
Authorization: Bearer {{accessTokenEndless}}
Content-Type: application/json

{
  "dayOfMonth": 6
}
