GET http://localhost:8080/dev/hallo

###
POST http://localhost:8080/token
Content-Type: application/json

{
  "username": "user",
  "password": "$2a$10$h5n4bzgvMfu0n1UROcXwau.pxLaSD2NvCEVrQUKxeBTR0NcyxfJ0C"
}

###
POST http://localhost:8080/dev/password
Content-Type: application/json

{
  "password": "password"
}
